# frozen_string_literal: true

source "https://rubygems.org"

gem "daemons"
gem "logger"
gem "openssl"

group :development, :test do
  gem "byebug"
  gem "pry"
  gem "pry-byebug"
end

group :test do
  gem "rspec"
  gem "rubocop", "~> 1.16.1"
end
